parser  : "babel-eslint"
parserOptions:
  ecmaVersion: 7
  sourceType: "module"
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true

extends : [
  "eslint:recommended",
  "standard",
  "standard-react"
]

env :
  es6: true,
  browser : true,
  node: true,
  mocha: true,

plugins: [
  "import",
  "react",
  "babel"
]

rules:
  comma-dangle : [1, "never"]
  func-names   : 0
  key-spacing  : 0
  space-before-function-paren : [2, "always"]
  no-else-return   : 0
  no-multi-spaces  : 0
  quotes           : [2, "single"]
  jsx-quotes       : [2, "prefer-double"]
  one-var          : 0
  "react/jsx-uses-react": "error"
  "react/jsx-uses-vars": "error"
  "react/jsx-curly-spacing": [2, "never"]
  "react/jsx-wrap-multilines": [2, {declaration: true, assignment: true, return: true}]